### PR TITLE
check before executing delegate method

### PR DESCRIPTION
**Pull request by skyline75489**

### CODE REVIEW

**Comment by Tangdixi** [comment]
Thanks for your PR @skyline75489

**Comment by skyline75489** [comment]
You're welcome :smile:

**Comment by skyline75489** [comment]
By the way, the `UITabBar` part in the example project is still crashing before this fix. I think you might want to update the example project, too.

**Comment by Tangdixi** [comment]
OK. Fixed!  
Now everything is fine ~

**Pull request merged**
